import { CanvasDocument, ImageLayer, TextLayer, ShapeLayer, DEFAULT_LAYER_EFFECTS, DEFAULT_IMAGE_ADJUSTMENTS } from './LayerModel';

// Embedded high-resolution vector SVG graphics for standalone zero-network demo reliability
const CYBER_SPEAKER_SVG = `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 600 600" width="600" height="600"><defs><linearGradient id="g1" x1="0%" y1="0%" x2="100%" y2="100%"><stop offset="0%" stop-color="%23EC4899"/><stop offset="100%" stop-color="%238B5CF6"/></linearGradient><linearGradient id="g2" x1="0%" y1="0%" x2="100%" y2="100%"><stop offset="0%" stop-color="%233B82F6"/><stop offset="100%" stop-color="%2306B6D4"/></linearGradient></defs><rect width="600" height="600" rx="30" fill="%231E1B4B"/><circle cx="300" cy="300" r="180" fill="url(%23g1)" opacity="0.85"/><circle cx="300" cy="300" r="120" fill="%230F172A"/><circle cx="300" cy="300" r="80" fill="url(%23g2)"/><path d="M220 180 L380 180 L340 420 L260 420 Z" fill="none" stroke="%2338BDF8" stroke-width="8" opacity="0.6"/><polygon points="300,240 350,330 250,330" fill="%23F43F5E"/></svg>`;

const COFFEE_CUP_SVG = `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 600 600" width="600" height="600"><defs><linearGradient id="cg" x1="0%" y1="0%" x2="100%" y2="100%"><stop offset="0%" stop-color="%23D97706"/><stop offset="100%" stop-color="%2378350F"/></linearGradient></defs><rect width="600" height="600" rx="30" fill="%2327272A"/><ellipse cx="300" cy="480" rx="200" ry="25" fill="%2318181B" opacity="0.8"/><rect x="180" y="220" width="240" height="230" rx="35" fill="url(%23cg)"/><ellipse cx="300" cy="220" rx="120" ry="40" fill="%23FDE68A"/><ellipse cx="300" cy="220" rx="100" ry="30" fill="%2392400E"/><path d="M420 280 C480 280 480 370 420 370" fill="none" stroke="%23D97706" stroke-width="24" stroke-linecap="round"/><path d="M270 160 Q290 120 270 90 M310 160 Q330 110 310 80 M350 160 Q370 120 350 90" stroke="%23FEF3C7" stroke-width="6" fill="none" stroke-linecap="round" opacity="0.6"/></svg>`;

const SAAS_DEVICE_SVG = `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 600 600" width="600" height="600"><defs><linearGradient id="sg" x1="0%" y1="0%" x2="100%" y2="100%"><stop offset="0%" stop-color="%232563EB"/><stop offset="100%" stop-color="%234F46E5"/></linearGradient></defs><rect width="600" height="600" rx="30" fill="%230F172A"/><rect x="80" y="100" width="440" height="300" rx="16" fill="%231E293B" stroke="%233B82F6" stroke-width="4"/><circle cx="110" cy="125" r="6" fill="%23EF4444"/><circle cx="130" cy="125" r="6" fill="%23F59E0B"/><circle cx="150" cy="125" r="6" fill="%2310B981"/><rect x="110" y="150" width="160" height="100" rx="8" fill="url(%23sg)"/><rect x="290" y="150" width="200" height="20" rx="4" fill="%23475569"/><rect x="290" y="180" width="160" height="15" rx="4" fill="%23334155"/><rect x="290" y="205" width="180" height="15" rx="4" fill="%23334155"/><path d="M120 360 L240 280 L320 320 L460 220" fill="none" stroke="%2310B981" stroke-width="8" stroke-linecap="round"/></svg>`;

export const SAMPLE_PROJECTS: CanvasDocument[] = [
  {
    id: 'project_summer_cyber',
    title: 'Neon Cyber Festival 2026',
    width: 1080,
    height: 1080,
    backgroundColor: '#090A0F',
    layers: [
      // 1. Background Box
      {
        id: 'layer_bg',
        name: 'Dark Studio Base',
        type: 'shape',
        shapeType: 'rect',
        x: 0,
        y: 0,
        width: 1080,
        height: 1080,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: true,
        fill: '#090A0F',
        stroke: 'transparent',
        strokeWidth: 0,
        cornerRadius: 0,
        semanticRole: 'background',
        effects: JSON.parse(JSON.stringify(DEFAULT_LAYER_EFFECTS)),
      } as ShapeLayer,

      // 2. Glow Accent Circle
      {
        id: 'layer_glow',
        name: 'Ambient Neon Glow',
        type: 'shape',
        shapeType: 'circle',
        x: 340,
        y: 180,
        width: 400,
        height: 400,
        rotation: 0,
        opacity: 0.35,
        visible: true,
        locked: false,
        fill: '#8B5CF6',
        stroke: 'transparent',
        strokeWidth: 0,
        cornerRadius: 0,
        semanticRole: 'shape',
        effects: {
          ...JSON.parse(JSON.stringify(DEFAULT_LAYER_EFFECTS)),
          glow: { enabled: true, color: '#EC4899', blur: 60 },
        },
      } as ShapeLayer,

      // 3. Main Subject Image
      {
        id: 'layer_subject',
        name: 'Cyber Core Visual',
        type: 'image',
        src: CYBER_SPEAKER_SVG,
        naturalWidth: 600,
        naturalHeight: 600,
        x: 290,
        y: 280,
        width: 500,
        height: 500,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        flipHorizontal: false,
        flipVertical: false,
        cornerRadius: 24,
        semanticRole: 'subject',
        adjustments: JSON.parse(JSON.stringify(DEFAULT_IMAGE_ADJUSTMENTS)),
        effects: {
          ...JSON.parse(JSON.stringify(DEFAULT_LAYER_EFFECTS)),
          shadow: { enabled: true, color: 'rgba(0,0,0,0.6)', blur: 30, offsetX: 0, offsetY: 15 },
        },
      } as ImageLayer,

      // 4. Headline Text
      {
        id: 'layer_headline',
        name: 'Festival Title',
        type: 'text',
        text: 'NEON WAVE\nFESTIVAL 2026',
        fontFamily: 'Outfit, sans-serif',
        fontSize: 72,
        fontWeight: 800,
        fontStyle: 'normal',
        textDecoration: 'none',
        textAlign: 'center',
        fill: '#FFFFFF',
        letterSpacing: 2,
        lineHeight: 1.05,
        x: 90,
        y: 90,
        width: 900,
        height: 160,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        semanticRole: 'headline',
        effects: {
          ...JSON.parse(JSON.stringify(DEFAULT_LAYER_EFFECTS)),
          shadow: { enabled: true, color: 'rgba(236,72,153,0.6)', blur: 20, offsetX: 0, offsetY: 4 },
        },
      } as TextLayer,

      // 5. Subtitle Text
      {
        id: 'layer_subtitle',
        name: 'Date & Location Copy',
        type: 'text',
        text: 'OCTOBER 24-26 • TOKYO DOME • 30+ LIVE ACTS',
        fontFamily: 'Inter, sans-serif',
        fontSize: 22,
        fontWeight: 600,
        fontStyle: 'normal',
        textDecoration: 'none',
        textAlign: 'center',
        fill: '#38BDF8',
        letterSpacing: 3,
        lineHeight: 1.2,
        x: 90,
        y: 810,
        width: 900,
        height: 40,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        semanticRole: 'subtitle',
        effects: JSON.parse(JSON.stringify(DEFAULT_LAYER_EFFECTS)),
      } as TextLayer,

      // 6. CTA Button Box
      {
        id: 'layer_cta_box',
        name: 'Get Tickets Button',
        type: 'shape',
        shapeType: 'rounded-rect',
        x: 370,
        y: 890,
        width: 340,
        height: 68,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        fill: '#EC4899',
        stroke: 'transparent',
        strokeWidth: 0,
        cornerRadius: 34,
        semanticRole: 'cta',
        effects: {
          ...JSON.parse(JSON.stringify(DEFAULT_LAYER_EFFECTS)),
          shadow: { enabled: true, color: 'rgba(236,72,153,0.5)', blur: 20, offsetX: 0, offsetY: 6 },
        },
      } as ShapeLayer,

      // 7. CTA Text
      {
        id: 'layer_cta_label',
        name: 'Button Label',
        type: 'text',
        text: 'RESERVE PASSES',
        fontFamily: 'Outfit, sans-serif',
        fontSize: 22,
        fontWeight: 700,
        fontStyle: 'normal',
        textDecoration: 'none',
        textAlign: 'center',
        fill: '#FFFFFF',
        letterSpacing: 2,
        lineHeight: 1,
        x: 370,
        y: 912,
        width: 340,
        height: 30,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        semanticRole: 'cta',
        effects: JSON.parse(JSON.stringify(DEFAULT_LAYER_EFFECTS)),
      } as TextLayer,
    ],
    selectedLayerIds: ['layer_headline'],
  },

  {
    id: 'project_artisan_coffee',
    title: 'Artisan Coffee Roasters Promo',
    width: 1080,
    height: 1080,
    backgroundColor: '#18181B',
    layers: [
      {
        id: 'coffee_bg',
        name: 'Dark Roast Canvas',
        type: 'shape',
        shapeType: 'rect',
        x: 0,
        y: 0,
        width: 1080,
        height: 1080,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: true,
        fill: '#18181B',
        stroke: 'transparent',
        strokeWidth: 0,
        cornerRadius: 0,
        semanticRole: 'background',
        effects: JSON.parse(JSON.stringify(DEFAULT_LAYER_EFFECTS)),
      } as ShapeLayer,
      {
        id: 'coffee_subject',
        name: 'Handcrafted Cup',
        type: 'image',
        src: COFFEE_CUP_SVG,
        naturalWidth: 600,
        naturalHeight: 600,
        x: 290,
        y: 260,
        width: 500,
        height: 500,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        flipHorizontal: false,
        flipVertical: false,
        cornerRadius: 16,
        semanticRole: 'subject',
        adjustments: JSON.parse(JSON.stringify(DEFAULT_IMAGE_ADJUSTMENTS)),
        effects: JSON.parse(JSON.stringify(DEFAULT_LAYER_EFFECTS)),
      } as ImageLayer,
      {
        id: 'coffee_title',
        name: 'Roast Headline',
        type: 'text',
        text: 'ETHIOPIAN YIRGACHEFFE\nSINGLE ORIGIN ROAST',
        fontFamily: 'Outfit, sans-serif',
        fontSize: 54,
        fontWeight: 700,
        fontStyle: 'normal',
        textDecoration: 'none',
        textAlign: 'center',
        fill: '#FDE68A',
        letterSpacing: 2,
        lineHeight: 1.15,
        x: 90,
        y: 80,
        width: 900,
        height: 140,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        semanticRole: 'headline',
        effects: JSON.parse(JSON.stringify(DEFAULT_LAYER_EFFECTS)),
      } as TextLayer,
      {
        id: 'coffee_badge',
        name: 'Price Badge',
        type: 'shape',
        shapeType: 'rounded-rect',
        x: 420,
        y: 840,
        width: 240,
        height: 54,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        fill: '#D97706',
        stroke: 'transparent',
        strokeWidth: 0,
        cornerRadius: 27,
        semanticRole: 'price',
        effects: JSON.parse(JSON.stringify(DEFAULT_LAYER_EFFECTS)),
      } as ShapeLayer,
      {
        id: 'coffee_badge_text',
        name: 'Price Label',
        type: 'text',
        text: 'SPECIAL $18.50',
        fontFamily: 'Inter, sans-serif',
        fontSize: 20,
        fontWeight: 700,
        fontStyle: 'normal',
        textDecoration: 'none',
        textAlign: 'center',
        fill: '#FFFFFF',
        letterSpacing: 1,
        lineHeight: 1,
        x: 420,
        y: 857,
        width: 240,
        height: 30,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        semanticRole: 'price',
        effects: JSON.parse(JSON.stringify(DEFAULT_LAYER_EFFECTS)),
      } as TextLayer,
    ],
    selectedLayerIds: ['coffee_title'],
  },

  {
    id: 'project_saas_launch',
    title: 'Cloud Platform Banner',
    width: 1200,
    height: 627,
    backgroundColor: '#0F172A',
    layers: [
      {
        id: 'saas_bg',
        name: 'Slate Background',
        type: 'shape',
        shapeType: 'rect',
        x: 0,
        y: 0,
        width: 1200,
        height: 627,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: true,
        fill: '#0F172A',
        stroke: 'transparent',
        strokeWidth: 0,
        cornerRadius: 0,
        semanticRole: 'background',
        effects: JSON.parse(JSON.stringify(DEFAULT_LAYER_EFFECTS)),
      } as ShapeLayer,
      {
        id: 'saas_subject',
        name: 'Product Dashboard Mockup',
        type: 'image',
        src: SAAS_DEVICE_SVG,
        naturalWidth: 600,
        naturalHeight: 600,
        x: 620,
        y: 90,
        width: 520,
        height: 450,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        flipHorizontal: false,
        flipVertical: false,
        cornerRadius: 16,
        semanticRole: 'subject',
        adjustments: JSON.parse(JSON.stringify(DEFAULT_IMAGE_ADJUSTMENTS)),
        effects: JSON.parse(JSON.stringify(DEFAULT_LAYER_EFFECTS)),
      } as ImageLayer,
      {
        id: 'saas_headline',
        name: 'Value Proposition',
        type: 'text',
        text: 'ACCELERATE YOUR\nAI AGENT CLOUD',
        fontFamily: 'Outfit, sans-serif',
        fontSize: 52,
        fontWeight: 800,
        fontStyle: 'normal',
        textDecoration: 'none',
        textAlign: 'left',
        fill: '#FFFFFF',
        letterSpacing: 1,
        lineHeight: 1.1,
        x: 70,
        y: 140,
        width: 520,
        height: 120,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        semanticRole: 'headline',
        effects: JSON.parse(JSON.stringify(DEFAULT_LAYER_EFFECTS)),
      } as TextLayer,
      {
        id: 'saas_sub',
        name: 'Description Copy',
        type: 'text',
        text: 'Deploy, orchestrate, and observe autonomous agents at lightning speed.',
        fontFamily: 'Inter, sans-serif',
        fontSize: 20,
        fontWeight: 400,
        fontStyle: 'normal',
        textDecoration: 'none',
        textAlign: 'left',
        fill: '#94A3B8',
        letterSpacing: 0,
        lineHeight: 1.4,
        x: 70,
        y: 280,
        width: 480,
        height: 60,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        semanticRole: 'subtitle',
        effects: JSON.parse(JSON.stringify(DEFAULT_LAYER_EFFECTS)),
      } as TextLayer,
      {
        id: 'saas_cta',
        name: 'Start Free Button',
        type: 'shape',
        shapeType: 'rounded-rect',
        x: 70,
        y: 380,
        width: 220,
        height: 56,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        fill: '#3B82F6',
        stroke: 'transparent',
        strokeWidth: 0,
        cornerRadius: 12,
        semanticRole: 'cta',
        effects: JSON.parse(JSON.stringify(DEFAULT_LAYER_EFFECTS)),
      } as ShapeLayer,
      {
        id: 'saas_cta_text',
        name: 'CTA Label',
        type: 'text',
        text: 'START FREE TRIAL',
        fontFamily: 'Inter, sans-serif',
        fontSize: 16,
        fontWeight: 700,
        fontStyle: 'normal',
        textDecoration: 'none',
        textAlign: 'center',
        fill: '#FFFFFF',
        letterSpacing: 1,
        lineHeight: 1,
        x: 70,
        y: 399,
        width: 220,
        height: 25,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        semanticRole: 'cta',
        effects: JSON.parse(JSON.stringify(DEFAULT_LAYER_EFFECTS)),
      } as TextLayer,
    ],
    selectedLayerIds: ['saas_headline'],
  },
];
